### PR TITLE
2 projects shoping carts - 1: SPA vue laravel, 2:laravel

### PR DESCRIPTION
**Pull request by alhaj-mhmd**

### CODE REVIEW

**Comment by az-iar** [comment]
@alhaj-mhmd please submit the files instead of one zip file

**Comment by alhaj-mhmd** [comment]
I uploaded 2 projects

**Comment by alhaj-mhmd** [comment]
@az-iar 
I uploaded 2 projects, thats why i made it zip

**Comment by az-iar** [comment]
@alhaj-mhmd can put in 2 separate folder instead

**Comment by alhaj-mhmd** [comment]
yes sure

**Pull request closed without merging**
